### ISSUE TITLE
The script does not work correctly if channels count more than one

### ISSUE THREAD

**Issue by apachx** [bachors/jQuery-Youtube-Channels-Playlist#6]
Hi.

How to embed (by channelid) two or more channels in one page? For example, this does not work correctly:
```
<div id="unix" data-ycp="UCoiS7s7HrE7bHNuzERi-FCQ"></div>
<div id="unix" data-ycp="UCANLZYMidaCbLQFWXBC95Jg"></div>
```

Because as a result, I see first channel - **UCoiS7s7HrE7bHNuzERi-FCQ**, but I do not see second channel - UCANLZYMidaCbLQFWXBC95Jg. How to fix that and make the script working for any number of videos?

**Comment by bachors** [comment]
Thanks,
you must use the class name to display multiple channels. 👍 

<pre><code>&lt;div class="whatever" data-ycp="UCoiS7s7HrE7bHNuzERi-FCQ"&gt;&lt;/div&gt;
&lt;div class="whatever" data-ycp="UCANLZYMidaCbLQFWXBC95Jg"&gt;&lt;/div&gt;
</code></pre>

<pre><code>$(".whatever").ycp(
     playlist = 10, // number of videos playlist count
     autoplay = false, // true or false
     related = false, // true or false
     apikey = 'AIzaSyCj2xxxxxxxxxxxx' // your google api key
);
</code></pre>

**Comment by apachx** [comment]
Thank you for your quick reply to my request! It works 👍
But I have another question: how to embed YouTube channels without Increasing page size, as described (for video) in this article: http://www.labnol.org/internet/light-youtube-embeds/27941/ ?

**Comment by bachors** [comment]
Thanks a lot @apachx , a very good idea. now I have to fix it.

I have changed the code [css](https://github.com/bachors/jQuery-Youtube-Channels-Playlist/blob/master/css/ycp.css) and [javascript](https://github.com/bachors/jQuery-Youtube-Channels-Playlist/blob/master/js/ycp.js). This will work if autoplay = false.

Best regards, Ican.

**Comment by apachx** [comment]
It works perfectly now. Thank you! That's really cool.
